### ISSUE TITLE
你们和之前的sota方法(sid,did)用的是一样的的数据集吗？

### ISSUE THREAD

**Issue by lzg1988** [TCL-AILab/Abandon_Bayer-Filter_See_in_the_Dark#3]
1. sid和did使用sid的0\*作为训练，你们用sid的0\*和2\*作为训练
2. sid和did使用0.1+0.04->10+30的配置，你们只使用0.1->10/30

使用更多的训练数据和复杂度更低的数据配置，直接对比是否公平？

**Comment by lzg1988** [comment]
https://github.com/MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time/issues/17
https://github.com/MohitLamba94/LLPackNet/issues/4

**Comment by xuwanyan1998** [comment]
> 1. sid和did使用sid的0*作为训练，你们用sid的0*和2*作为训练
> 2. sid和did使用0.1+0.04->10+30的配置，你们只使用0.1->10/30
> 
> 使用更多的训练数据和复杂度更低的数据配置，直接对比是否公平？

首先感谢您对我们之前工作的关注，对于您所提出的问题1，在原始SID的训练代码中，他们是将0*作为训练集（train），2*作为验证集（validation）（用来在训练过程中调整超参数），1*作为测试集（test）；在我们的代码中我们舍弃了验证集，因此将训练集和验证集的数据合并用于训练，对于测试集的数据在训练过程中并未用来训练模型，训练流程确实和原始SID流程有差异。

其次关于问题2，在检查了SID代码后发现原SID代码中使用[0.1+0.04](https://github.com/cchen156/Learning-to-See-in-the-Dark/blob/607d8d6b9321a6af28312167e3793bc5b94b7742/train_Sony.py#L145)两种曝光作为训练和测试，我们自己模型训练的pipeline主要参考了[
Restoring-Extremely-Dark-Images-In-Real-Time](https://github.com/MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time)，其中关于SID模型的训练测试数据仅使用[0.1](https://github.com/MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time/blob/4a6722c5f788b56bed657cbc1045d2ef34f0e307/train_test_ours/train_test_SID_CVPR_18/train.py#L41)一种曝光，我也注意到你在RED中对此问题的提问[#17](https://github.com/MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time/issues/17)，这一个问题确实存在，对于SID数据集上的数据我们只训练了自己的模型，其余数据基本都来自对应的文章当中，我们也是参考了其中的一个工作作为自己的训练pipeline，我们也不能确保其余所有模型训练设置和原始SID一致，建议其余模型的训练设置参考对应原始代码。对于其余模型在我们所提出的MCR数据集的比较，我们都是用七组长短曝光对作为训练测试数据，得出的结果也与在SID数据集中一致。

希望以上可以解答您的问题！

**Comment by lzg1988** [comment]
1. 根据你们的代码，你们应该是使用0*和2*作为训练，1*作为验证和测试吧。训练集作为验证集，很容易过拟合。
2. [RED](https://github.com/MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time/issues/18)和[LLPACK](https://github.com/MohitLamba94/LLPackNet/issues/4)的问题我还在和作者沟通，我也看到你们之前也发现了这个[issue](https://github.com/MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time/issues/6)，训练pipeline和SID的确不同。

个人猜测按sid的数据和流程训练，因为训练数据只有161个而且考虑了0.1+0.04+0.033s的短曝光输入，效果没有RED的(训练数据181个+只考虑0.1s的短曝光)好，不知道你们那边是不是这个结果:)

**Comment by xuwanyan1998** [comment]
确实是验证集和测试集使用了相同的数据，之前的训练流程不够规范化。
在MCR数据集上，利用相同的数据进行训练，SID确实会比RED好一些，一方面我认为可能是SID模型本身就比RED大很多（RED主要缩小了模型，提升了实时性），另一方面我们在MCR数据集上训练RED流程也不能确保与原始代码完全一致，可能RED其中也会有一些tricks

**Comment by lzg1988** [comment]
在你们的论文里面的SID数据集上，你们是和RED一样用的0.1s的数据还是用的所有的数据(0.1+0.033+0.04)的数据

https://github.com/MohitLamba94/LLPackNet/issues/4
