### ISSUE TITLE
is that fair to compare with previous work when using different testing data

### ISSUE THREAD

**Issue by lzg1988** [TCL-AILab/Abandon_Bayer-Filter_See_in_the_Dark#4]
I tested your pretrained model SID_weights_690000.
If testing only 0.1 short exposure data, the psnr and ssim is 29.69 and 0.7962, better than your metrics in paper(29.65, 0.797).
However, previous sota method(sid and did) is using the whole test data, including **0.1s, 0.04s and 0.033 shot exposure data**.
So,we test your model in the same testing data as sid, **the metric is much worse. The psnr and ssim is 23.9432 and 0.6831.**

Maybe it is not fair to compare the methods by using different testing data. 
Could you provide **more solid** result?

**Comment by xingbod** [comment]
Applying the model to SID directly is suboptimal as no Gray RAW is available.
